### ISSUE TITLE
useGetTimeOfDay hook

### ISSUE THREAD

**Issue by SalemC** [samharvey44/blue-action-forum#1]
Since this hook doesn't return an actual time of day, but a time period, I think it would make sense calling it `useGetTimePeriodOfDay`, or even `useGetCurrentTimePeriod`.

https://github.com/samharvey44/blue-action-forum/blob/5dfe3f48b2b2aa7ea4c067b95c3cd9ec21519964/resources/js/hooks/timeOfDay/get/index.ts#L3

Thoughts?

**Comment by samharvey44** [comment]
I think you're right about the naming convention not being quite right, I'll have a think and fix this
