### ISSUE TITLE
PHP import ordering

### ISSUE THREAD

**Issue by SalemC** [samharvey44/blue-action-forum#2]
I'd personally reverse the order of these imports, separating them by vendor imports and local imports, then order by the length of the import in descending order.

https://github.com/samharvey44/blue-action-forum/blob/5dfe3f48b2b2aa7ea4c067b95c3cd9ec21519964/app/Http/Controllers/Auth/SignupController.php#L5-L8

Just a recommendation, I'm pedantic with code styling - sorry! :)

**Comment by samharvey44** [comment]
Will change for consistency 👍
